

- name: Installing Neutron (Ubuntu)
  apt:
    name:
      - neutron-server
      - neutron-plugin-ml2
      - neutron-openvswitch-agent
      - neutron-dhcp-agent
      - neutron-metadata-agent
    state: latest

- name: Configure Neutron
  replace:
    dest: /etc/neutron/neutron.conf
    regexp: connection = mysql+pymysql://neutron:NEUTRON_DBPASS@controller/neutron
    replace: connection = mysql+pymysql://neutron:admin123@controller/neutron
    backup: yes

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/neutron.conf
    line: core_plugin = ml2
    state: present
    backup: yes

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/neutron.conf
    regexp: 'service_plugins = '
    state: absent
    backup: yes

- name: Conf Neutron
  replace:
    dest: /etc/neutron/neutron.conf
    regexp: transport_url = rabbit://openstack:RABBIT_PASS@controller
    replace: transport_url = rabbit://openstack:admin123@controller
    backup: yes

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/neutron.conf
    line: 'auth_strategy = keystone'
    state: present
    backup: yes

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/neutron.conf
    insertafter: '\[keystone_authtoken\]'
    line: "{{ item }}"
    state: present
    backup: yes

  with_items:
    - www_authenticate_uri = http://controller:5000
    - auth_url = http://controller:5000
    - memcached_servers = controller:11211
    - auth_type = password
    - project_domain_name = Default
    - user_domain_name = Default
    - project_name = service
    - username = neutron
    - password = admin123

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/neutron.conf
    insertafter: '\[DEFAULT\]'
    line: "{{ item }}"
    state: present
    backup: yes

  with_items:
    - notify_nova_on_port_status_changes = true
    - notify_nova_on_port_data_changes = true

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/neutron.conf
    insertafter: '\[nova\]'
    line: "{{ item }}"
    state: present
    backup: yes

  with_items:
    - auth_url = http://controller:5000
    - auth_type = password
    - project_domain_name = Default
    - user_domain_name = Default
    - region_name = RegionOne
    - project_name = service
    - username = nova
    - password = admin123

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/neutron.conf
    line: 'lock_path = /var/lib/neutron/tmp'
    state: present
    backup: yes

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    line: 'type_drivers = flat,vlan'
    state: present
    backup: yes

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    regexp: 'tenant_network_types ='
    state: absent
    backup: yes

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    insertafter: '\[ml2\]'
    line: " {{ item }}"
    state: present
    backup: yes

  with_items:
    - mechanism_drivers = openvswitch
    - extension_drivers = portsecurity

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    line: 'flat_networks = provider'
    state: present
    backup: yes

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    regexp: 'bridge_mappings = provider: PROVIDER_INTERFACE_NAME'
    line: 'bridge_mappings = provider:LocalMachine'
    backup: yes

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    insertafter: '\[securitygroup\]'
    line: "{{ item }}"
    state: present
    backup: yes

  with_items:
    - enable_security_group = true
    - firewall_driver = openvswitch

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/dhcp_agent.ini
    insertafter: '\[DEFAULT\]'
    line: "{{ item }}"
    state: present
    backup: yes

  with_items:
    - interface_driver = openvswitch
    - dhcp_driver = neutron.agent.linux.dhcp.Dnsmasq
    - enable_isolated_metadata = true

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/metadata_agent.ini
    line: 'nova_metadata_host = controller'
    state: present
    backup: yes

- name: Configure Neutron
  lineinfile:
    dest: /etc/neutron/metadata_agent.ini
    regexp: 'metadata_proxy_shared_secret = METADATA_SECRET'
    line: 'metadata_proxy_shared_secret = admin123'
    state: present
    backup: yes

- name: Confgiure Neutron
  lineinfile:
    dest: /etc/nova/nova.conf
    insertafter: '\[neutron\]'
    line: "{{ item }}"
    state: present
    backup: yes

  with_items:
    - auth_url = http://controller:5000
    - auth_type = password
    - project_domain_name = Default
    - user_domain_name = Default
    - region_name = RegionOne
    - project_name = service
    - username = neutron
    - password = admin123
    - service_metadata_proxy = true
    - metadata_proxy_shared_secret = admin123
